### ISSUE TITLE
AST node ranges are not always correct

### ISSUE THREAD

**Issue by eventualbuddha** [michaelficarra/CoffeeScriptRedux#335]
This is a pretty minimal failing example showing how it fails. This is with current master (a40829b584a242d8c4350e2c51c6f2b875a3624e).

```coffee
->
  a.b
```

The `Program`, `Block`, and `Function` are all fine but the range of the `Block` inside the function is incorrect, which affects everything (in this case) after it:

```
Program  raw = "->\n  a.b", source[0...8] = "->\n  a.b"
Block  raw = "->\n  a.b", source[0...8] = "->\n  a.b"
Function  raw = "->\n  a.b", source[0...8] = "->\n  a.b"
Block  raw = "a.b", source[6...9] = ".b"
MemberAccessOp  raw = "a.b", source[6...9] = ".b"
Identifier  raw = "a", source[6...7] = "."
```

The above output was generated by this program, which may be run directly from the CoffeeScriptRedux repository root (e.g. as bug.js):

```js
const CoffeeScript = require('./');

const red = 31;
const green = 32;

const source = '->\n  a.b';
const ast = CoffeeScript.parse(source, { raw: true }).toBasicObject();

traverse(ast, function(node) {
  const raw = node.raw;
  const sourceInRange = source.slice(node.range[0], node.range[1]);
  console.log(
    '%s  raw = %s, source[%d...%d] = %s',
    color(raw === sourceInRange ? green : red, node.type),
    shortPrettyString(raw),
    node.range[0],
    node.range[1],
    shortPrettyString(sourceInRange)
  );
});

function traverse(ast, callback) {
  callback(ast);
  for (var key in ast) {
    var value = ast[key];
    if (value && typeof value.type === 'string') {
      traverse(value, callback);
    } else if (Array.isArray(value)) {
      value.forEach(function(child) {
        if (child && typeof child.type === 'string') {
          traverse(child, callback);
        }
      });
    }
  }
}

function color(code, message) {
  return '\x1b[' + code + 'm' + message + '\x1b[0m';
}

function shortPrettyString(string) {
  return JSON.stringify(string.length > 20 ? string.slice(0, 20) + '…' : string);
}
```

**Comment by michaelficarra** [comment]
It's very strange that we get the `raw` value correct but the range incorrect. Especially since we're just [using PEG.js's `line`, `column`, and `offset` functions](https://github.com/michaelficarra/CoffeeScriptRedux/blob/a40829b584a242d8c4350e2c51c6f2b875a3624e/src/grammar.pegcoffee#L237-L246). Unfortunately, this is in one of the hairier parts of the code (read: there's a nasty hack to skip counting of context-free-CoffeeScript control characters).

**Comment by eventualbuddha** [comment]
Just in case it's helpful to you or anyone else who runs into this, here's what I'm using to fix the ranges. It's probably pretty inefficient but so far it's been sufficient for my needs:

```js
// Visit every node to fix its range, assumes each node has a
// `_parent` property that refers to its parent node. This is intended
// to operate on the result of `toBasicObject()` on the parsed AST.
traverse(ast, function(node) {
  if (!node.range) { return; }

  if (node._parent) {
    node.range[0] += node._parent._offset;
    node.range[1] += node._parent._offset;
  }

  if (node.raw !== source.slice(node.range[0], node.range[1])) {
    node._offset = fixRange(node, source);
  } else {
    node._offset = 0;
  }
});

function fixRange(node, source) {
  var index = -1;
  var expectedStart = node.range[0];
  var minimumOffsetIndex = -1;
  var minimumOffset = Infinity;

  while ((index = source.indexOf(node.raw, index + 1)) >= 0) {
    if (minimumOffsetIndex < 0) {
      minimumOffsetIndex = index;
      minimumOffset = Math.abs(expectedStart - minimumOffsetIndex);
    } else {
      var thisOffset = Math.abs(expectedStart - index);
      if (thisOffset < minimumOffset) {
        minimumOffset = thisOffset;
        minimumOffsetIndex = index;
      }
    }
  }

  if (minimumOffsetIndex < 0) {
    throw new Error('unable to find location for node: ' + JSON.stringify(node.raw));
  }

  node.range[0] = minimumOffsetIndex;
  node.range[1] = minimumOffsetIndex + node.raw.length;

  return minimumOffsetIndex - expectedStart;
}
```

**Comment by eventualbuddha** [comment]
Actually, it looks like it's even worse. Some nodes that ought to have `range` and `raw` do not have either, such as when parsing `"a#{b}"`:

```js
> parse('"a#{b}"', { raw: true }).toBasicObject().body.statements[0]
{ type: 'ConcatOp',
  line: 1,
  column: 1,
  raw: '"a#{b}"',
  range: [ 0, 7 ],
  left:
   { type: 'String',
     line: 1,
     column: 2,
     data: 'a' },
  right:
   { type: 'Identifier',
     line: 1,
     column: 5,
     raw: 'b',
     range: [ 4, 5 ],
     data: 'b' } }
```

**Comment by eventualbuddha** [comment]
Okay, I think I've figured out why this is happening. I'm pretty sure it's due to the "context-free-CoffeeScript control characters" you mentioned. When an input string is pre-processed a number of characters are added, so this:

```js
->
  a.b
```

Becomes this:

```js
->
  a.b
```

Those extra characters are what is causing the `range` property to be incorrect, as it's reporting the range inside the *preprocessed* input, not the *original* input. I can think of a few ways to work around this, but I'm not sure how to fix it. Thoughts, @michaelficarra?

**Comment by michaelficarra** [comment]
Ah yes, now I remember. We fixed that issue in #117 (https://github.com/michaelficarra/CoffeeScriptRedux/commit/1f314eb80ff2393bc9508dd1f66205ad33ba6c3d) (though, using an extremely hacky approach). I would not be surprised if it broke when upgrading PEGjs, if not for the fact that we do have tests for it. I still can't think of a better way to solve this problem than the hack from #117.

**Comment by eventualbuddha** [comment]
I don't believe the problem is exactly the same. That commit does in fact fix line and column numbers, but doesn't fix offsets. I have a workaround from a commit that links to this issue that basically recomputes the range info based on the line and column numbers.

Am I missing something?

**Comment by michaelficarra** [comment]
Oh you're right, I didn't notice it only fixed line/column but not offset.

Your commit looks awesome! Would we be able to also get rid of that nasty hack in the parser?
