### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by dynamix** [michaelficarra/CoffeeScriptRedux#336]
Hey guys,

quick question - what is the status of CoffeeScriptRedux? Will this ever be 2.0 or is it more or less dead and its better to stick with https://github.com/jashkenas/coffeescript? I googled around for quite a while and searched through twitter but couldn't find a definite answer - I'm sure I must have missed something.

Asking because ember-script (which seems to be dead, too) was based on CoffeeScriptRedux.

Ciao,
Martin

**Comment by fourq** [comment]
from what I heard, it's dead. #RIP

**Comment by erisdiscord** [comment]
@fourq Really?? Where'd you hear that?

**Comment by michaelficarra** [comment]
Not from any official sources, that's where. Anyone is free to work on this project. I stopped working on it after a disagreement between myself and the other CoffeeScript maintainers (long after this project's sponsored time period was over). I don't see a future for the CoffeeScript language without adoption of ES6 features. Unfortunately, I was the only one that believed we should adopt the semantics of any equivalent features in ES6: classes, default parameters, destructuring, comprehensions (while they were still ES6 track), etc. So because I no longer use the language for my own projects, I am not motivated to work on it. But there's nothing stopping anyone from opening issues and sending PRs. The vast majority of users are just unwilling to contribute.

**Comment by lydell** [comment]
> The vast majority of users are just unwilling to contribute.

That's the important point here. There are too few users and contributors. I've contributed a bit to the project and it's very nicely designed so it's not that hard! If you're interestes in the project, then by all means go ahead and work on it!

IMO, the project is mostly done. What needs to be done is:

- `super` (there's a PR for it)
- CoffeeScript 1.7+ features
- Polishing
- Work on the "jashkenas/coffeescript is too permissive, redux is too strict" issues

I hope that both projects could live alongside each other, without one replacing the other.

**Comment by michaelficarra** [comment]
:heart: @lydell. Thanks for all you've been doing with these projects lately.

**Comment by vendethiel** [comment]
> So because I no longer use the language for my own projects, I am not motivated to work on it.

That's the same for me (not that I've been a huge contributer to either compilers, though) : I havn't used coffee in well over 2 years (and LiveScript in the past year), so my interest in either projects have dwindled down (and really, I don't have much interest in web anymore). 

But yeah, :+1: to @lydell for his awesome contributions :).

**Comment by fourq** [comment]
@erisdiscord a few different irc channels. =/

**Comment by alexgorbatchev** [comment]
I'm currently considering forking coffeescript to do proper implementation of ES6 stuff... I'm baffled by lack of progress on that side.

**Comment by erisdiscord** [comment]
@alexgorbatchev forking CSR or the original? I've poked around with both codebases and this one seems to be a lot easier to navigate. Either way, do drop a comment here if you decide to go through with it.

**Comment by alexgorbatchev** [comment]
havent looked into which specific repo to use as base yet

**Comment by dynamix** [comment]
@lydell @michaelficarra - thanks for the clarification. (OT : did you just switch back to plain JS (>=ES6)?)

**Comment by michaelficarra** [comment]
@dynamix: I've been using ES6 for work JS (compiled to ES5 through 6to5) and PureScript for fun.

**Comment by erichonkanen** [comment]
has anyone continued to work on this? the web is full of people proclaiming es6 > coffeescript but imo it's quite the opposite.. I hope development and support continues despite the hipster es6 fad

**Comment by aurium** [comment]
Well...
If it was possible to plug parser extensions, and plug external AST to JS code generator, on CS compiler, initiatives like IcedCoffee, ember-script, and ES6 support could survive integrated to the CS ecosystem. And if the ES6 prove it is a good idea (*i believe so*), may be easier to push it to the CS core, on the future.

**Comment by igl** [comment]
After also doing the switch from coffee to babel in our company, i am not too excited about ES6 anymore. Precompilers still have a future. The features they have to tackle are going to be harder but with TC39 focused on imperative features, transforming javascript yet again more into java, there is plenty of stuff that needs fixing by the community.

Annoying: `function (foo, ...rest, callback)` rest argument must be the last one. (`callback = rest.pop()`ugh! :cry:)
Silly: `const foo = 1; foo = 2;` === No Error. Assignment expr. returns 2. *Wat?!*
Half assed: `@annotation` Only planned for class and their proto functions. No functions, no vars no imports, more java.
Consistency: `import { a as b } from 'foo'`,`const { a : b } = foo`, `((a, ...b) => a).length === 1` *Wat?!*
Sad: Instead of channels or proper tasks we get: Promises. Shoot me now!

And boy did i NOT miss these tails:

            })
        ], callback)
    }

**Comment by nmccready** [comment]
> Having said that: Always bet on JS creating the need for precompilers.

@igl amen

**Comment by JimPanic** [comment]
*bump*

Has anyone got plans/ideas/anything regarding this dilemma? I'm currently looking into starting with ES6, but I'd rather have a coffee6 for the reasons everyone else here stated as well. :)

**Comment by erichonkanen** [comment]
coffeescript for life! not drinking the babel/es6/7 coolaid yet!

**Comment by JimPanic** [comment]
I didn't have time yet to dive in deep into the codebase, but I also have no idea where to start.

Is there any guideline as to where to start in the light of making the current CS syntax output (node-supported) ES6 code? What parts would I have to look at/change?

I'd really like to keep CS in my toolbox, vanilla JS is *so* tedious to write. :-1:

**Comment by danielbayley** [comment]
@JimPanic 

There already a couple of projects on that:
https://github.com/rainforestapp/decaf
https://github.com/decaffeinate/decaffeinate

**Comment by JimPanic** [comment]
@danielbayley I'd much rather continue to use coffee (redux?) instead of just converting my code. So I was basically asking how to contribute.

**Comment by danielbayley** [comment]
> I'd much rather continue to use coffee

Same! I _hate_ vanilla JS. But those are 2 projects (there might be more) already converting CS to ES6 so why duplicate effort? I believe the _decaf_ repo is being moved into a new @CoffeeScript organisation, but hasn't happened yet. There's plenty of discussion on this [CS > ES6] over on the original CS repo.

I really wish everyone in CS camp would just come together and kill this meme that CS is dead and we all have to be _coerced_ into writing ES6.

**Comment by vendethiel** [comment]
> Is there any guideline as to where to start in the light of making the current CS syntax output (node-supported) ES6 code? What parts would I have to look at/change?

You'd need to first make sure Escodegen supports ES6. [Thankfully, it does](https://github.com/estools/escodegen/blob/master/escodegen.js#L2092)

**Comment by JimPanic** [comment]
I haven't even looked at classes in ES6 so far tbh, I'm usually not using them. But keeping semantics in CS is probably a good idea and it might be a step in the future to remove this in favour of something else maybe.

I'll try to decipher the codebase of coffeescriptredux and see where to go from there.

@danielbayley are those projects able to run code like coffee does now (cli interface, load coffee modules on the fly)? From the README it seems they're mostly used as transit projects to migrate coffeescript codebases to ES6. (Which is not my goal!)

**Comment by danielbayley** [comment]
@JimPanic I'm not sure to be honest, I would at least speak to @juliankrispel about _decaf_ though.

**Comment by JimPanic** [comment]
@danielbayley as far as I can see *decaf* is a superset of coffee. It uses a different library to generate JS code apparently. And with this, it generates ES.next (ES2017 right now, I guess?) code. I'd like to target ES6 - or ultimately and ideally be able to drop in different generators.

Lets see. :)

**Comment by remoteportal** [comment]
Hey folks,

(My favorite language is CS—I’ve been using it for my “day job” for two years and have chosen CoffeeScript Redux for a project I’m moonlighting with at home.)

In addition to that I’m envisioning an entirely new domain-specific language based on CS Redux for my home project.  

It’s NOT writing CoffeeScript Redux, per se, but compiler work; I’m looking for someone who is good at PEG.js to fork the Redux project and customize to my needs.

Does anyone reading this have a desire to work remotely on a project for (guessing?) perhaps 40 hours?  I’m just one guy (not a company) but can obviously compensate per hour for your work.

ANY help would be appreciated; even a few hours of your paid coding could get me on the right path if you’re not interested in working the entire small project. 

I figure you folks can crank this out MUCH quicker than I can.

Pete Alvin
it@onlyup.com <mailto:it@onlyup.com>
@remoteportal
https://github.com/remoteportal <https://github.com/remoteportal>
mobile 704.804.4786

**Comment by rattrayalex** [comment]
Like @remoteportal I am interested in building a new language, and this repo seems like the best starting point. 

Unlike @remoteportal I don't think I could pay for the help 😄 

Personally I'm interested in a statically-typed, whitespace-sensitive, light-syntax language – think "coffeescript for typescript/flow". 

@michaelficarra do you have any interest in creating a coffeescript-like derivative? From the ES6-related issues on the main coffee repo, it seems much of the community was on your side. I'm sure I'm not the only one who likes ES6 features and CS syntax; anything you were to produce would probably attract a following.

**Comment by forivall** [comment]
@rattrayalex I'm currently working on github.com/forivall/tacoscript - for typing, I'll basically support flow annotations, but right now it's just the core es6 syntax. I'm _not_ using PEG since I want to basically do CST transformations to preserve whitespace (which is what I want to get "done" before I want to get people to try it out).

**Comment by DomVinyard** [comment]
I think it would be helpful if this conversation came back around to reinvigorating coffeescript rather than inventing new technologies.

**Comment by rattrayalex** [comment]
You know what, @DomVinyard ? That's a good point ;-)

I've gone ahead and created https://github.com/coffeescript6/discuss to do just that. CoffeeScript really is a fantastic language and while it could use some upgrades, I think you're right that we don't necessarily need to start from scratch here. 

Let's start getting some ideas on paper!

**Comment by JimPanic** [comment]
Thank you for putting this up, @rattrayalex !

**Comment by juliankrispel** [comment]
I'm still working on an integration with coffeescript and decaf btw. Just have been super busy lately, ETA: 2 months
