### ISSUE TITLE
REPL tests broken under iojs / new nodejs

### ISSUE THREAD

**Issue by ef4** [michaelficarra/CoffeeScriptRedux#342]
Under iojs v1.6.2, the REPL tests fail with EBADF, most likely related to this warning:

```
child_process: customFds option is deprecated, use stdio instead.
```

**Comment by michaelficarra** [comment]
I'm aware: https://github.com/michaelficarra/CoffeeScriptRedux/issues/319

**Comment by ef4** [comment]
Apologies, I did an issue search but "node" was the wrong term, as it's rather overloaded here. :stuck_out_tongue:
