### ISSUE TITLE
-r command line option doesn't seem to work

### ISSUE THREAD

**Issue by danielbayley** [michaelficarra/CoffeeScriptRedux#358]
If i do `coffee -er path/to/module[.coffee] 'command'` either nothing happens or I get an error, whereas if I switch to using the original `coffee` binary it does work as expected.

As far as I can tell, the [original upstream issue](https://github.com/jashkenas/coffeescript/issues/1035) (which was fixed in [this](https://github.com/TrevorBurnham/coffee-script/commit/7815138386ee1fbbcc3c6cfd3d904658ff8a2b10) PR) still exists in Redux.

**Comment by michaelficarra** [comment]
What is the `-r` flag supposed to do? I don't think that's a flag in our CLI.

**Comment by danielbayley** [comment]
@michaelficarra From the `coffee` [help](http://coffeescript.org/documentation/docs/command.html);
`-r, --require [MODULE*] require the given module before eval or REPL`

**Comment by michaelficarra** [comment]
This project's CLI is not compatible with that one's.

**Comment by danielbayley** [comment]
> This project's CLI is not compatible with that one's.

I get that, but is this project not aiming for feature parity?

**Comment by michaelficarra** [comment]
No, it compiles the same language. The CLI, REPL, etc. are separate.
