### ISSUE TITLE
feature request: compile to go and php

### ISSUE THREAD

**Issue by falafflepotatoe** [michaelficarra/CoffeeScriptRedux#359]
seriously
i would love to write coffee->go and php, go would have an auto type guessing algorithm  and support an extra keyword for the type if it cant guess (ex: i int=123) 
(the type guessing algo is simple, int/float/string are ez to guess, and everything else declare once *somewhere* and the functions that use it will guess it from that)
also sh/bash would be sweet

barring the type issues, how hard would this be? thoughts on how hard that would be?

**Comment by vendethiel** [comment]
The js-nodes are here: https://github.com/michaelficarra/CoffeeScriptRedux/blob/master/src/js-nodes.coffee

If you manage to replace the code generating javascript (that's escodegen, afaik) with something that takes the same AST format (well, that's gonna be a JS ast, you'll definitely need to change things up), I don't think too much of the compiler internals are tied to JS (you'll need to translate helpers and all, of course)

**Comment by falafflepotatoe** [comment]
@vendelthiel thanks that helps a lot.
